In [1]:
using Gurobi, CSV, DataFrames, JuMP, LinearAlgebra, Distributions, Random, GLMNet

In [2]:
trainx = CSV.read("x_training_stable.csv",DataFrame)
trainy = CSV.read("y_training_stable.csv",DataFrame,header=0)
#testx = CSV.read("airfoil_X_test.csv",DataFrame)
#testy = CSV.read("airfoil_Y_test.csv",DataFrame)

4474×1 DataFrame
  Row │ Column1   
      │ Float64   
──────┼───────────
    1 │  1023.33
    2 │   311.594
    3 │   351.542
    4 │  1609.9
    5 │  1078.6
    6 │   386.83
    7 │   203.735
    8 │   564.598
    9 │   107.86
   10 │  1070.61
   11 │  1062.62
  ⋮   │     ⋮
 4465 │  8323.83
 4466 │ 10236.7
 4467 │  9275.93
 4468 │ 10306.6
 4469 │  9779.94
 4470 │  9664.75
 4471 │ 10993.7
 4472 │ 11445.1
 4473 │ 12117.6
 4474 │ 13087.0
 4453 rows omitted

In [3]:
trainxmat = Matrix(trainx)
trainyarr = Vector(trainy[:,1])

4474-element Vector{Float64}:
  1023.3346
   311.5944
   351.5424
  1609.9044
  1078.596
   386.8298
   203.7348
   564.5984
   107.8596
  1070.6064
  1062.6168
   910.8144
  1609.9044
     ⋮
 10072.8882
  8994.958
  8323.8316
 10236.675
  9275.9256
 10306.584
  9779.9362
  9664.7528
 10993.6896
 11445.102
 12117.56
 13086.9648

In [7]:
trainxmat_modified=trainxmat[:,1:4]
trainxmat_others=trainxmat[:,5:size(trainxmat)[2]]


4474×44 Matrix{Float64}:
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  …   0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0     26.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  …   0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0     15.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  …   0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ⋮           

In [4]:
trainxmat_modified

4474×4 Matrix{Float64}:
  7.155    0.168527    33.6874  11.0
 12.35     0.0418025   34.8216  14.0
 10.85     0.0480043  117.581   15.0
  9.3      0.0422563  124.439   26.0
 12.15     0.062276    37.9532   9.0
  9.0      0.0692291   55.9614  11.0
 16.75     0.0137113  100.267   15.0
 12.7929   0.0977687  142.45    28.0
  6.385    0.140328   109.16    15.0
 18.2      0.16296     43.5086  26.0
  7.97     0.0400711   87.3514  11.0
  8.71     0.139796    47.2376   4.0
  8.85     0.112571   122.039   26.0
  ⋮                             
 12.7929   0.044445   245.28    28.0
 16.75     0.0814851  258.099   11.0
 20.25     0.0363997  219.348   11.0
 12.7929   0.0345844  248.375   28.0
  5.695    0.0659609  259.265    6.0
 12.7929   0.0306933  228.035   28.0
  6.825    0.059847   262.523   16.0
 12.6      0.0743386  255.536    6.0
 12.7929   0.0888399  254.267   28.0
 12.7929  -0.969538   253.036   28.0
 12.7929   0.0142956  242.651   28.0
 12.7929   0.0105509  234.996   28.0

In [4]:
#NOT USED
#stable_y=stable_all_train_val_proc[:,4]

#stable_x=select!(stable_all_train_val_proc,Not(:Item_Outlet_Sales))


LoadError: UndefVarError: stable_all_train_val_proc not defined

In [2]:
trainxmat = Matrix(trainx)
trainyarr = Vector(trainy[:,1])

#testxmat = Matrix(testx)
#testyarr = Vector(testy[:,1])


#lasso_model = glmnetcv(trainxmat, trainyarr, intercept=false)


Least Squares GLMNet Cross Validation
83 models for 15 predictors in 10 folds
Best λ 0.000 (mean loss 0.372, std 0.009)

In [7]:
#Question 1(a)

trainxmat = Matrix(trainx)
trainyarr = Vector(trainy[:,1])

testxmat = Matrix(testx)
testyarr = Vector(testy[:,1])


lasso_model = glmnetcv(trainxmat, trainyarr, intercept=false)


lasso_best_ind = argmin(lasso_model.meanloss)
lasso_betas = lasso_model.path.betas[:,lasso_best_ind]

irsq = lasso_model.path.dev_ratio[lasso_best_ind]
println("In sample R^2 is: $irsq")

predictions = GLMNet.predict(lasso_model, testxmat)

orsq = 1 - ((sum((testyarr.-predictions).^2)) / (sum((testyarr.-mean(trainyarr)).^2)))
println("Out sample R^2 is: $orsq")


In sample R^2 is: 0.6337612813617132
Out sample R^2 is: 0.6377673043458182


In [12]:
#Question 1(b)

cor(trainxmat)
#It seems like correlation between variable 1 and 8 is very high, we double check
cor(trainxmat[:,1], trainxmat[:,8])
#True so we remove column 8
trainxmat2 = trainxmat[:, 1:end .!= 8]
testxmat2 = testxmat[:, 1:end .!= 8]

cor(trainxmat2)
#correlation between 2 and 5 > 0.7 so we remove 5
trainxmat2 = trainxmat2[:, 1:end .!= 5]
testxmat2 = testxmat2[:, 1:end .!= 5]

cor(trainxmat2)
#correlation between 2 and 9 > 0.7 so we remove 9
trainxmat2 = trainxmat2[:, 1:end .!= 9]
testxmat2 = testxmat2[:, 1:end .!= 9]

cor(trainxmat2)
#correlation between 2 and 9 > 0.7 so we remove 9
trainxmat2 = trainxmat2[:, 1:end .!= 9]
testxmat2 = testxmat2[:, 1:end .!= 9]

cor(trainxmat2)
#correlation between 2 and 11 > 0.7 so we remove 11
trainxmat2 = trainxmat2[:, 1:end .!= 11]
testxmat2 = testxmat2[:, 1:end .!= 11]

cor(trainxmat2)
#correlation between 3 and 9 > 0.7 so we remove 9
trainxmat2 = trainxmat2[:, 1:end .!= 9]
testxmat2 = testxmat2[:, 1:end .!= 9]

cor(trainxmat2)
cor(trainxmat2[:,5], trainxmat2[:,7])
#correlation between 5 and 7 > 0.7 so we remove 7
trainxmat2 = trainxmat2[:, 1:end .!= 7]
testxmat2 = testxmat2[:, 1:end .!= 7]

cor(trainxmat2)
cor(trainxmat2[:,7], trainxmat2[:,8])
#correlation between 7 and 8 > 0.7 so we remove 8
trainxmat2 = trainxmat2[:, 1:end .!= 8]
testxmat2 = testxmat2[:, 1:end .!= 8]

cor(trainxmat2)

problem = 0
m,n = size(cor(trainxmat2))
for i=1:m
    for j=1:n
        if(cor(trainxmat2)[i,j] > 0.7 && i!=j)
            print("Correlation between variables $i and $j is > 0.7")
            problem = 1
        end
    end
end

if (problem == 0)
    print("No more strong correlation and a total of $m variables")
end

No more strong correlation and a total of 7 variables

In [13]:
lasso_model2 = glmnetcv(trainxmat2, trainyarr, intercept=false)

lasso_best_ind2 = argmin(lasso_model2.meanloss)
lasso_betas2 = lasso_model2.path.betas[:,lasso_best_ind2]

irsq2 = lasso_model2.path.dev_ratio[lasso_best_ind2]
println("In sample R^2 is: $irsq2")

predictions2 = GLMNet.predict(lasso_model2, testxmat2)

orsq2 = 1 - ((sum((testyarr.-predictions2).^2)) / (sum((testyarr.-mean(trainyarr)).^2)))
println("Out sample R^2 is: $orsq2")

In sample R^2 is: 0.559143431150576
Out sample R^2 is: 0.5784134408726588


In [8]:
function holistic(x, y, weirdr, M)
    
    n, p = size(x)

    m = Model(Gurobi.Optimizer)
    
    set_optimizer_attribute(m, "OutputFlag", 0) 
    
    @variable(m, beta[1:p])
    @variable(m, beta0)
    @variable(m, z[1:p], Bin)
    @variable(m, q[1:p] >= 0)
    @variable(m, t[1:n] >= 0)
    
    @constraint(m, sum(z) <= 10)
    pby4 = trunc(Int, 4) ##CHECK IF NOT WORKS +++++++++++++++++++++++++++++++++++++++ 4 or 1
    @constraint(m, [i=1:pby4], sum(z[(i-1)*4+j] for j=1:4) == 1)
    @constraint(m, z[5] == 1) #ensure visibility feature chosen
    
    @constraint(m, [i=1:p], -M*z[i] <= beta[i])
    @constraint(m, [i=1:p], beta[i] <= M*z[i])
    @constraint(m, [i=1:p], beta[i] <= q[i])
    @constraint(m, [i=1:p], -beta[i] <= q[i])

    for i=2:p
        for j=1:(i-1)
            if (cor(x[:,i],x[:,j]) > 0.7)
                @constraint(m, z[i]+z[j] <= 1)
            end
        end
    end
    
    @constraint(m, [i=1:n], (y[i] - sum(x[i,j]*beta[j] for j=1:p) - beta0) <= t[i])
    @constraint(m, [i=1:n], -(y[i] - sum(x[i,j]*beta[j] for j=1:p) - beta0) <= t[i])
    
    @objective(m, Min, 0.5 * sum(t[i]^2 for i=1:n) + weirdr * sum(q[j] for j=1:p))
    optimize!(m)
        
    obj = JuMP.objective_value(m)
    beta0 = JuMP.value(beta0)
    betas = JuMP.value.(beta)
    z = JuMP.value.(z)
        
    return obj, beta0, betas, z
end

holistic (generic function with 1 method)

In [4]:
#add origional variables back in that were not transformed
#trainxmat=orig 4 columns

function creatematrices(trainxmat,  eps)
    ntrain, ptrain = size(trainxmat)
    #ntest, ptest = size(testxmat)

    modtrainxmat = zeros(ntrain, 4*ptrain)
    #modtestxmat = zeros(ntest, 4*ptest)

    for i = 1:(4)
        modtrainxmat[:,4*(i-1)+1] = trainxmat[:,i]
        modtrainxmat[:,4*(i-1)+2] = trainxmat[:,i].^2
        modtrainxmat[:,4*(i-1)+3] = sqrt.(abs.(trainxmat[:,i]))
        modtrainxmat[:,4*(i-1)+4] = log.(abs.(trainxmat[:,i]) .+ eps)

#         modtestxmat[:,4*(i-1)+1] = testxmat[:,i]
#         modtestxmat[:,4*(i-1)+2] = testxmat[:,i].^2
#         modtestxmat[:,4*(i-1)+3] = sqrt.(abs.(testxmat[:,i]))
#         modtestxmat[:,4*(i-1)+4] = log.(abs.(testxmat[:,i]) .+ eps)
        end

    return modtrainxmat #, modtestxmat
end

creatematrices (generic function with 1 method)

In [2]:
using Gurobi, CSV, DataFrames, JuMP, LinearAlgebra, Distributions, Random, GLMNet

In [9]:
first_four_transformed = creatematrices(trainxmat_modified,  10e-6) #removed tesstxmat
exttrainxmat=hcat(first_four_transformed, trainxmat_others)
#



using Tables
CSV.write("exttrainxmat.csv",  Tables.table(exttrainxmat), writeheader=false)


"exttrainxmat.csv"

In [3]:
trainy = CSV.read("y_training_stable.csv",DataFrame,header=0)
trainyarr = Vector(trainy[:,1])

exttrainxmat= CSV.read("exttrainxmat.csv",DataFrame,header=0)


4474×60 DataFrame
  Row │ Column1  Column2   Column3  Column4  Column5     Column6      Column7  ⋯
      │ Float64  Float64   Float64  Float64  Float64     Float64      Float64  ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │  7.155    51.194   2.67488  1.96781   0.168527   0.0284015    0.410521 ⋯
    2 │ 12.35    152.522   3.51426  2.51366   0.0418025  0.00174745   0.204457
    3 │ 10.85    117.722   3.29393  2.38417   0.0480043  0.00230441   0.219099
    4 │  9.3      86.49    3.04959  2.23002   0.0422563  0.00178559   0.205563
    5 │ 12.15    147.623   3.48569  2.49733   0.062276   0.00387831   0.249552 ⋯
    6 │  9.0      81.0     3.0      2.19723   0.0692291  0.00479266   0.263114
    7 │ 16.75    280.562   4.09268  2.8184    0.0137113  0.000187999  0.117095
    8 │ 12.7929  163.657   3.57671  2.54889   0.0977687  0.00955872   0.31268
    9 │  6.385    40.7682  2.52686  1.85395   0.140328   0.019692     0.374604 ⋯
   10 │ 18.2     331.24    4.26615  2.90142   0.16296    0.0265561    0.403684
   11 │  7.97     63.5209  2.82312  2.07569   0.0400711  0.0016057    0.200178
  ⋮   │    ⋮        ⋮         ⋮        ⋮         ⋮            ⋮          ⋮     ⋱
 4465 │ 20.25    410.062   4.5      3.00816   0.0363997  0.00132494   0.190787
 4466 │ 12.7929  163.657   3.57671  2.54889   0.0345844  0.00119608   0.185969 ⋯
 4467 │  5.695    32.433   2.38642  1.73959   0.0659609  0.00435084   0.256829
 4468 │ 12.7929  163.657   3.57671  2.54889   0.0306933  0.000942079  0.175195
 4469 │  6.825    46.5806  2.61247  1.92059   0.059847   0.00358166   0.244636
 4470 │ 12.6     158.76    3.54965  2.5337    0.0743386  0.00552622   0.272651 ⋯
 4471 │ 12.7929  163.657   3.57671  2.54889   0.0888399  0.00789254   0.29806
 4472 │ 12.7929  163.657   3.57671  2.54889  -0.969538   0.940004     0.984651
 4473 │ 12.7929  163.657   3.57671  2.54889   0.0142956  0.000204363  0.119564
 4474 │ 12.7929  163.657   3.57671  2.54889   0.0105509  0.000111323  0.102718 ⋯
                                                53 columns and 4453 rows omitted

In [ ]:
weirdroptions = [1]
lengthoptions = length(weirdroptions)
savemses = zeros(lengthoptions)
M = 10000

first_four_transformed = creatematrices(trainxmat_modified,  10e-6) #removed tesstxmat
exttrainxmat=hcat(first_four_transformed, trainxmat_others)
#exttrainxmat = creatematrices(trainxmat_modified,  10e-6) #removed tesstxmat


#trainyarr
#testyarr

n, p = size(exttrainxmat)
numfolds = 3
foldsamps = sample(1:numfolds, n, replace = true)

for i = 1:numfolds
    
    println("i = $i")
    traintrainx = exttrainxmat[[x for x in 1:n if foldsamps[x] != i],:]
    print("A")
    trainvalx = exttrainxmat[[x for x in 1:n if foldsamps[x] == i],:]
    print("B")
    
    
    traintrainy = trainyarr[[x for x in 1:n if foldsamps[x] != i],:]
    print("C")
    trainvaly = trainyarr[[x for x in 1:n if foldsamps[x] == i],:]
    print("D")
    for j = 1:lengthoptions
        println("j = $j")
        r = weirdroptions[j]
        obj, beta0, betas, z = holistic(traintrainx, traintrainy, r, M)
        predictions = trainvalx * betas .+ beta0
        mse = mean((predictions .- trainvaly).^2)
        savemses[j] = savemses[j] + mse
    end
end

i = 1
AB

In [28]:
M=100
r=0.1#

n, p = size(exttrainxmat)
numfolds = 10
foldsamps = sample(1:numfolds, n, replace = true)

function cross_val(rho, fold,M)
   # first_four_transformed = creatematrices(trainxmat_modified,  10e-6) #removed tesstxmat
   # exttrainxmat=hcat(first_four_transformed, trainxmat_others)


   


    traintrainx = exttrainxmat[[x for x in 1:n if foldsamps[x] != fold],:]
    trainvalx = exttrainxmat[[x for x in 1:n if foldsamps[x] == fold],:]
    traintrainy = trainyarr[[x for x in 1:n if foldsamps[x] != fold],:]
    trainvaly = trainyarr[[x for x in 1:n if foldsamps[x] == fold],:]
    print("D")


    print("A")
    obj, beta0, betas, z = holistic(traintrainx, traintrainy, rho, M)
    print("B")
    predictions = Matrix(trainvalx) * betas .+ beta0
    mse = mean((predictions .- trainvaly).^2)
    #savemses[j] = savemses[j] + mse
    
    return(beta0, betas, z, trainvalx, trainvaly, mse)
end

cross_val (generic function with 1 method)

In [30]:
beta0, betas, z, trainvalx, trainvaly, mse = cross_val(0.1, 1, 100);

DAAcademic license - for non-commercial use only - expires 2022-08-18
B

In [ ]:
loop over CV, rho and folds for 10fold CV 

In [27]:
#predictions = trainvalx * betas .+ beta0
Matrix(trainvalx) * betas  .+ beta0

430-element Vector{Float64}:
 3039.736544072305
  743.0789994088126
 2218.9408946997105
 1674.316627137875
 1373.2261597115103
 1957.5854129906375
 2489.480305649628
 3926.0000671938237
  505.4898327759055
 1298.2523812159893
 3255.942832548813
 1719.2216677356441
  477.2333865006548
    ⋮
 4310.05201245978
 4243.145499767079
 2928.431636181129
 4618.00777791233
 3332.850501722952
 4849.588958104796
 3157.16117524279
 3683.2417934263344
 3812.415150561054
 2819.4656141971577
 4586.995132834587
 4354.6148984127585

In [17]:
findall(x->x==1,z)

10-element Vector{Int64}:
  3
  8
  9
 14
 36
 38
 40
 44
 46
 52

In [19]:
trainyarr

4473-element Vector{Float64}:
   311.5944
   351.5424
  1609.9044
  1078.596
   386.8298
   203.7348
   564.5984
   107.8596
  1070.6064
  1062.6168
   910.8144
  1609.9044
  1454.1072
     ⋮
 10072.8882
  8994.958
  8323.8316
 10236.675
  9275.9256
 10306.584
  9779.9362
  9664.7528
 10993.6896
 11445.102
 12117.56
 13086.9648

In [ ]:
traintrainy = trainyarr[[x for x in 1:n if foldsamps[x] != i],:]
    

In [ ]:
println("List of MSE: $savemses")
bestr = weirdroptions[argmin(savemses)]
println("Best WeirdR: $bestr")

In [ ]:
#We see that the selected hyperparameter is at the end of the range, so check a new range

weirdroptions2 = [2, 5, 9, 15, 30, 50, 100]
lengthoptions2 = length(weirdroptions2)
savemses2 = zeros(lengthoptions2)
M = 10000

exttrainxmat, exttestxmat = creatematrices(trainxmat, testxmat, 10e-6)
#trainyarr
#testyarr

n, p = size(exttrainxmat)
numfolds = 10
foldsamps = sample(1:numfolds, n, replace = true)

for i = 1:numfolds
    
    println("i = $i")
    traintrainx = exttrainxmat[[x for x in 1:n if foldsamps[x] != i],:]
    trainvalx = exttrainxmat[[x for x in 1:n if foldsamps[x] == i],:]
    traintrainy = trainyarr[[x for x in 1:n if foldsamps[x] != i],:]
    trainvaly = trainyarr[[x for x in 1:n if foldsamps[x] == i],:]
    
    for j = 1:lengthoptions2
        println("j = $j")
        r = weirdroptions2[j]
        obj, beta0, betas, z = holistic(traintrainx, traintrainy, r, M)
        predictions = trainvalx * betas .+ beta0
        mse = mean((predictions .- trainvaly).^2)
        savemses2[j] = savemses2[j] + mse
    end
end

In [ ]:
println("List of MSE: $savemses")
bestr = weirdroptions2[argmin(savemses2)]
println("Best WeirdR: $bestr")

In [ ]:
#we train a final model with the chosen parameter 

finobj, finbeta0, finbetas, finz = holistic(exttrainxmat, trainyarr, bestr, M)
        
predictiontrain = exttrainxmat * finbetas .+ finbeta0
predictiontest = exttestxmat * finbetas .+ finbeta0

irsq2 = 1 - ((sum((trainyarr.-predictiontrain).^2)) / (sum((trainyarr.-mean(trainyarr)).^2)))
println("In sample R^2 is: $irsq2")

orsq2 = 1 - ((sum((testyarr.-predictiontest).^2)) / (sum((testyarr.-mean(trainyarr)).^2)))
println("Out sample R^2 is: $orsq2")